### ISSUE TITLE
bower install after generating a bower-shrinkwrap-resolver.json is failing if a bower component's version is "*"

### ISSUE THREAD

**Issue by Ashwin117** [shyiko/bower-shrinkwrap-resolver#1]
Receiving the following error

`bower ENORESTARGET  No version found that was able to satisfy *`

**Comment by shyiko** [comment]
@Ashwin117 Hi. Did you close this ticket by mistake? We stumbled upon this regression too so it does exist. Should be fixed tomorrow, though.

**Comment by shyiko** [comment]
Alright, now it's fixed.

**Comment by Ashwin117** [comment]
Thanks @shyiko : Yes, did close by mistake. My fault and thanks for being so proactive on it :+1:
