### ISSUE TITLE
util.debuglog is causing issues when compiling the program with node v0.10

### ISSUE THREAD

**Issue by Ashwin117** [shyiko/bower-shrinkwrap-resolver#2]
util.debuglog works for v0.12, but we would like to use bower shrinkwrap for apps that use v0.10.

**Comment by shyiko** [comment]
@Ashwin117 There you go :)

**Comment by shyiko** [comment]
v0.3.1

**Comment by Ashwin117** [comment]
@shyiko : Thanks man. Will take a look at this. Thanks for getting back so quickly.
