### ISSUE TITLE
Ability to generate shrinkwrap through command other than 'bower install'?

### ISSUE THREAD

**Issue by brainmonger** [shyiko/bower-shrinkwrap-resolver#7]
Does this exist and I maybe missed it? The documentation mentions that 'bower install' is used to generate the shrinkwrap. For my particular case, my team would like to have another command generate the shrinkwrap because we don't want to inadvertently generate it in in lower environments.

Any feedback is appreciated, thank you.

**Comment by shyiko** [comment]
Hi. Not at the moment. The closest thing I can think of right now is to add another `.bowerrc` config option (like [this one](https://github.com/shyiko/bower-shrinkwrap-resolver/blob/master/src/index.js#L46)) to have shrinkwrap generation off by default + add cli flag (like `--force-shrinkwrap`) to force shrinkwrap regeneration when needed.

**Comment by brainmonger** [comment]
@shyiko thank you. I see in index.js where I can check for forceShrinkwrap (`var forceShrinkwrap = !!~argv.indexOf('--force-shrinkwrap'`).. would you be able to give me a pointer on how to update the `.bowerrc` config to turn on the `--force-shrinkwrap` option so that it will run when I type `bower-install`?

I'm not spotting how to add command line options to `.bowerrc` yet: https://bower.io/docs/config/

**Comment by shyiko** [comment]
@brainmonger Sure. https://github.com/shyiko/bower-shrinkwrap-resolver/blob/master/src/index.js#L46. Here `bower-shrinkwrap-resolver` is checking whether `strict-shrinkwrap` is set (e.g. .bowerrc `{"bower-shrinkwrap-resolver": {"strict-shrinkwrap": true}}`).

**Comment by brainmonger** [comment]
@shyiko Thank you, I made the update locally with the one you mentioned above. The only difference is I'm calling the var `allowShrinkwrap` and set it to `true` by default. Then, checking against the `.bowerrc` version. If you want me to submit a PR just let me know, otherwise I can always just fork it. Thanks again.

**Comment by shyiko** [comment]
@brainmonger PR would work ;)

**Comment by shyiko** [comment]
Released as 0.5.0 (to disable shrinkwrap by default add `{"bower-shrinkwrap-resolver": {"shrinkwrap": false}}` to the .bowerrc; to force shrinkwrap from the command line - use `--shrinkwrap`).
