### ISSUE TITLE
Cannot read property 'shrinkwrap' of undefined

### ISSUE THREAD

**Issue by graemechapman** [shyiko/bower-shrinkwrap-resolver#9]
After updating to version 0.5.0, bower install started crashing out with this error.

It looks like this is caused [here](https://github.com/shyiko/bower-shrinkwrap-resolver/blob/master/src/index.js#L24), if the bowerrc does not have a `bower-shrinkwrap-resolver` property. `rc` then resolves to `undefined`, but this line is expecting it to be an object.

**Comment by graemechapman** [comment]
Also, I think the documentation needs to be updated with usage for the `bower-shrinkwrap-resolver` property in .bowerrc 😉

**Comment by shyiko** [comment]
@graemechapman Thank you for the ticket. And yes, you are right - readme.md should be updated.

**Comment by shyiko** [comment]
@graemechapman Fixed in 0.5.1. readme.md will be updated shortly.

**Comment by graemechapman** [comment]
Nice one, 10 minutes from issue report to release! Thanks @shyiko 👍
